import { TopicNode } from "../types";
import { TOPIC_SUBTOPICS } from "./subtopicsData";

export const CELL_MODULES = [
  {
    id: "I",
    name: "Módulo I: Envolturas & Membrana Celular",
    shortName: "Módulo I: Envolturas",
    block: "Citología I",
    range: "Temas 01 - 08",
    color: "from-cyan-500 to-blue-600",
    borderColor: "border-cyan-500/40",
    glowColor: "rgba(6, 182, 212, 0.4)",
  },
  {
    id: "II",
    name: "Módulo II: Citosol, Citoesqueleto & Organoides",
    shortName: "Módulo II: Citosol",
    block: "Citología I",
    range: "Temas 09 - 13",
    color: "from-emerald-500 to-teal-600",
    borderColor: "border-emerald-500/40",
    glowColor: "rgba(16, 185, 129, 0.4)",
  },
  {
    id: "III",
    name: "Módulo III: Endomembranas & Organelas",
    shortName: "Módulo III: Organelas",
    block: "Citología I",
    range: "Temas 14 - 21",
    color: "from-amber-500 to-orange-600",
    borderColor: "border-amber-500/40",
    glowColor: "rgba(245, 158, 11, 0.4)",
  },
  {
    id: "IV",
    name: "Módulo IV: Arquitectura Nuclear & Carioteca",
    shortName: "Módulo IV: Núcleo",
    block: "Citología II",
    range: "Temas 22 - 25",
    color: "from-purple-500 to-indigo-600",
    borderColor: "border-purple-500/40",
    glowColor: "rgba(168, 85, 247, 0.4)",
  },
  {
    id: "V",
    name: "Módulo V: Cromatina, Nucleolo & Genoma",
    shortName: "Módulo V: Cromatina",
    block: "Citología II",
    range: "Temas 26 - 30",
    color: "from-rose-500 to-pink-600",
    borderColor: "border-rose-500/40",
    glowColor: "rgba(244, 63, 94, 0.4)",
  },
] as const;

export const CITOLOGY_PILLARS = [
  {
    id: "ALL" as const,
    title: "Todos los Temas",
    badge: "30 Nodos",
    description: "Recorrido integral por Citología I y Citología II",
  },
  {
    id: "CITO_I" as const,
    title: "Citología I: Membrana & Organelas",
    badge: "Temas 01 - 21",
    description: "Arquitectura celular, transporte de membrana, citosol y organelas",
  },
  {
    id: "CITO_II" as const,
    title: "Citología II: Núcleo & Genoma",
    badge: "Temas 22 - 30",
    description: "El núcleo celular interfásico, poros, cromatina, nucleolo y cromosomas",
  },
] as const;

export const STUDY_LEVELS = [
  {
    id: 1 as const,
    name: "Nivel 1: La Intuición",
    shortName: "Nivel 1: Intuición",
    badge: "Nivel 1",
    tagline: "Analogía viva • Sentido común • Comprensión sin frustración",
    description: "Para entender qué está pasando y por qué existe en la naturaleza, usando analogías visuales que tu cerebro no olvidará.",
    color: "from-emerald-400 to-teal-500",
    textColor: "text-emerald-300",
    borderColor: "border-emerald-500/30",
    bgMuted: "bg-emerald-950/30 border-emerald-500/20",
  },
  {
    id: 2 as const,
    name: "Nivel 2: La Maquinaria",
    shortName: "Nivel 2: Maquinaria",
    badge: "Nivel 2",
    tagline: "Piezas reales • Proteínas clave • Secuencia paso a paso",
    description: "Cómo funciona por dentro: las moléculas reales, las proteínas ejecutoras y la secuencia viva del proceso.",
    color: "from-amber-400 to-orange-500",
    textColor: "text-amber-300",
    borderColor: "border-amber-500/30",
    bgMuted: "bg-amber-950/30 border-amber-500/20",
  },
  {
    id: 3 as const,
    name: "Nivel 3: Trampas de Examen",
    shortName: "Nivel 3: Examen",
    badge: "Nivel 3",
    tagline: "Desarmando trampas • Términos en cristiano • Autoevaluación",
    description: "Dominio crítico: dónde suelen equivocarse en los exámenes, las diferencias sutiles explicadas y autoevaluación interactiva.",
    color: "from-sky-400 to-indigo-500",
    textColor: "text-sky-300",
    borderColor: "border-sky-500/30",
    bgMuted: "bg-sky-950/30 border-sky-500/20",
  },
] as const;

const INITIAL_TOPICS_RAW: Omit<TopicNode, "subtopics">[] = [
  // ==========================================
  // CITOLOGÍA I - MÓDULO I: ENVOLTURAS Y MEMBRANA (01 - 08)
  // ==========================================
  {
    id: "tema-01",
    number: 1,
    title: "Teoría Celular e Historia",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Historia & Postulados",
    keywords: "Hooke, Leeuwenhoek, Schleiden, Schwann, Virchow, Omnis cellula e cellula",
    essentialConcept: "Postulados fundamentales: la célula como unidad anatómica, funcional, genética y de origen de todos los seres vivos.",
    x: 90,
    y: 110,
    connections: ["tema-02"],
  },
  {
    id: "tema-02",
    number: 2,
    title: "Célula Procariota vs. Eucariota",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Clasificación General",
    keywords: "Nucleoide, plásmido, ribosomas 70S vs 80S, mesosomas, carioteca, citoesqueleto",
    essentialConcept: "Diferencias biológicas: presencia de envoltura nuclear, compartimentación de organelas y tipo de ribosomas.",
    x: 220,
    y: 90,
    connections: ["tema-01", "tema-05", "tema-06"],
  },
  {
    id: "tema-03",
    number: 3,
    title: "Glucocálix Animal",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Envoltura Celular",
    keywords: "Oligosacáridos, glicoproteínas, glicolípidos, antigenismo, histocompatibilidad, carga negativa",
    essentialConcept: "Cubierta glucídica externa responsable del reconocimiento celular, antigenismo de grupos sanguíneos y adhesión tisular.",
    x: 370,
    y: 70,
    connections: ["tema-06"],
  },
  {
    id: "tema-04",
    number: 4,
    title: "Pared Celular Vegetal y Plasmodesmos",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Envoltura Celular",
    keywords: "Celulosa, hemicelulosa, pectina, lámina media, pared primaria, secundaria, lignina, plasmodesmos",
    essentialConcept: "Armazón rígido de microfibrillas de celulosa que otorga soporte mecánico, turgencia e interconexión citoplasmática.",
    x: 520,
    y: 70,
    connections: ["tema-06"],
  },
  {
    id: "tema-05",
    number: 5,
    title: "Pared Celular Bacteriana (Gram + y Gram -)",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Procariotas",
    keywords: "Peptidoglucano, mureína, ácido teicoico, lipopolisacárido LPS, tinción Gram, periplasma",
    essentialConcept: "Gram positivas con capa gruesa de peptidoglucano y ácidos teicoicos vs Gram negativas con membrana externa y LPS.",
    x: 130,
    y: 210,
    connections: ["tema-02"],
  },
  {
    id: "tema-06",
    number: 6,
    title: "Membrana Plasmática: Mosaico Fluido",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Membrana Celular",
    keywords: "Singer y Nicolson, fosfolípidos anfipáticos, colesterol, balsas lipídicas, permeabilidad selectiva",
    essentialConcept: "Bicapa lipídica anfipática en continuo movimiento con proteínas integrales y periféricas con permeabilidad selectiva.",
    x: 440,
    y: 150,
    connections: ["tema-03", "tema-04", "tema-07", "tema-08", "tema-09"],
  },
  {
    id: "tema-07",
    number: 7,
    title: "Transporte Pasivo: Difusión y Ósmosis",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Fisiología de Membrana",
    keywords: "A favor de gradiente, sin gasto de ATP, difusión simple, facilitada, acuaporinas, plasmólisis, turgencia",
    essentialConcept: "Paso espontáneo de solutos y agua a favor del gradiente electroquímico sin consumo de energía celular (ATP).",
    x: 600,
    y: 120,
    connections: ["tema-06"],
  },
  {
    id: "tema-08",
    number: 8,
    title: "Transporte Activo: Bombas y Masa",
    module: "I",
    moduleName: "Envolturas & Membrana",
    category: "Fisiología de Membrana",
    keywords: "Contra gradiente, gasto de ATP, bomba Na+/K+ ATPasa, endocitosis, fagocitosis, pinocitosis, exocitosis",
    essentialConcept: "Transporte en contra de gradiente con gasto de ATP (bomba Na+/K+) y translocación vesicular en masa.",
    x: 740,
    y: 140,
    connections: ["tema-06", "tema-09"],
  },

  // ==========================================
  // CITOLOGÍA I - MÓDULO II: CITOSOL Y ORGANOIDES (09 - 13)
  // ==========================================
  {
    id: "tema-09",
    number: 9,
    title: "Citosol, Ciclosis y Coloides Celulares",
    module: "II",
    moduleName: "Citosol & Organoides",
    category: "Matriz Citoplasmática",
    keywords: "Citosol, hialoplasma, estado sol-gel, ciclosis, homeostasis, solutos celulares",
    essentialConcept: "Medio acuoso intracelular donde se disuelven metabolitos y se produce la corriente citoplasmática (ciclosis).",
    x: 420,
    y: 250,
    connections: ["tema-06", "tema-10", "tema-12"],
  },
  {
    id: "tema-10",
    number: 10,
    title: "Citoesqueleto y Motores Moleculares",
    module: "II",
    moduleName: "Citosol & Organoides",
    category: "Estructura Dinámica",
    keywords: "Microfilamentos de actina, filamentos intermedios, microtúbulos de tubulina, quinesina, dineína",
    essentialConcept: "Red tridimensional de filamentos proteicos que mantiene la forma celular, guía el tráfico vesicular y permite la motilidad.",
    x: 280,
    y: 260,
    connections: ["tema-09", "tema-11", "tema-14"],
  },
  {
    id: "tema-11",
    number: 11,
    title: "Centrosoma, Centríolos y Cilios/Flagelos",
    module: "II",
    moduleName: "Citosol & Organoides",
    category: "Organoides Microtubulares",
    keywords: "Centro organizador de microtúbulos MTOC, diplosoma 9x3 tripletes, axonema 9+2 dobletes, nexina, corpúsculo basal",
    essentialConcept: "Organizador de microtúbulos celular sin membrana; forma el aparato locomotor (cilios y flagelos) y el huso celular.",
    x: 160,
    y: 330,
    connections: ["tema-10"],
  },
  {
    id: "tema-12",
    number: 12,
    title: "Ribosomas Celulares (70S y 80S)",
    module: "II",
    moduleName: "Citosol & Organoides",
    category: "Organoides de Traducción",
    keywords: "ARN ribosomal, subunidad mayor y menor, polisomas, enlace peptídico, peptidil transferasa, 70S vs 80S",
    essentialConcept: "Complejos ribonucleoproteicos sin membrana encargados de la traducción y síntesis de proteínas celulares.",
    x: 340,
    y: 330,
    connections: ["tema-09", "tema-14", "tema-28"],
  },
  {
    id: "tema-13",
    number: 13,
    title: "Inclusiones Citoplasmáticas",
    module: "II",
    moduleName: "Citosol & Organoides",
    category: "Depósitos Celulares",
    keywords: "Gránulos de glucógeno hepático, gotas lipídicas, granos de almidón amiloplastos, cristales de oxalato cálcico",
    essentialConcept: "Acúmulos inertes de sustancias de reserva energética o desecho metabólico desprovistos de membrana celular.",
    x: 190,
    y: 260,
    connections: ["tema-09"],
  },

  // ==========================================
  // CITOLOGÍA I - MÓDULO III: ENDOMEMBRANAS Y ORGANELAS (14 - 21)
  // ==========================================
  {
    id: "tema-14",
    number: 14,
    title: "Retículo Endoplasmático Rugoso (RER)",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Sistema Endomembranas",
    keywords: "Riboforinas I y II, síntesis de proteínas de exportación, membrana y lisosomales, glucosilación inicial",
    essentialConcept: "Cisternas membranosas tachonadas de ribosomas que sintetizan, pliegan y transfieren proteínas al complejo de Golgi.",
    x: 280,
    y: 420,
    connections: ["tema-12", "tema-15", "tema-16", "tema-23"],
  },
  {
    id: "tema-15",
    number: 15,
    title: "Retículo Endoplasmático Liso (REL)",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Sistema Endomembranas",
    keywords: "Síntesis de lípidos, fosfolípidos, colesterol, detoxificación celular citocromo P450, retículo sarcoplásmico, Ca2+",
    essentialConcept: "Túbulos membranosos sin ribosomas dedicados a la síntesis de lípidos, desintoxicación de fármacos y secuestro de calcio.",
    x: 140,
    y: 430,
    connections: ["tema-14", "tema-16"],
  },
  {
    id: "tema-16",
    number: 16,
    title: "Aparato de Golgi y Secreción Celular",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Sistema Endomembranas",
    keywords: "Dictiosomas, cara cis formación, cara trans maduración, glucosilación terminal, tráfico vesicular COP-I/II, secreción",
    essentialConcept: "Centro empaquetador y distribuidor; madura proteínas, añade glúcidos terminales y genera vesículas secretoras y lisosomas.",
    x: 400,
    y: 430,
    connections: ["tema-14", "tema-15", "tema-17"],
  },
  {
    id: "tema-17",
    number: 17,
    title: "Lisosomas y Digestión Celular",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Organelas Digestivas",
    keywords: "Hidrolasas ácidas, pH 5.0, bomba H+-ATPasa, heterofagia, autofagia reciclaje, autólisis",
    essentialConcept: "Vesículas con enzimas digestivas ácidas especializadas en degradar nutrientes, bacterias fagocitadas y reciclar organelas viejas.",
    x: 480,
    y: 360,
    connections: ["tema-16"],
  },
  {
    id: "tema-18",
    number: 18,
    title: "Peroxisomas y Glioxisomas",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Microcuerpos Oxidativos",
    keywords: "Catalasa, oxidasa, peróxido de hidrógeno H2O2, beta-oxidación de ácidos grasos VLCFA, ciclo del glioxilato",
    essentialConcept: "Organelas que degradan toxinas y ácidos grasos generando H2O2, el cual es descompuesto en agua y oxígeno por la enzima catalasa.",
    x: 520,
    y: 440,
    connections: ["tema-09"],
  },
  {
    id: "tema-19",
    number: 19,
    title: "Vacuola Vegetal y Turgencia (Tonoplasto)",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Organelas Vegetales",
    keywords: "Tonoplasto, presión de turgencia, pigmentos antocianinas, cristales de oxalato, almacén de agua",
    essentialConcept: "Compartimento volumétrico vegetal delimitado por el tonoplasto que regula la presión osmótica y almacena pigmentos y agua.",
    x: 330,
    y: 520,
    connections: ["tema-16"],
  },
  {
    id: "tema-20",
    number: 20,
    title: "Mitocondria: Ultraestructura y ATP",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Organelas Energéticas",
    keywords: "Doble membrana, crestas mitocondriales, matriz o mitosol, ADN circular mARN, mitorribosomas 70S, ATP sintasa",
    essentialConcept: "Central energética semiautónoma de doble membrana con ADN propio; realiza la fosforilación oxidativa para sintetizar ATP.",
    x: 180,
    y: 530,
    connections: ["tema-09"],
  },
  {
    id: "tema-21",
    number: 21,
    title: "Plastidios y Cloroplasto",
    module: "III",
    moduleName: "Endomembranas & Organelas",
    category: "Organelas Energéticas",
    keywords: "Tilacoides, granas, estroma, clorofila, pigmentos fotosintéticos, ADN plastidial, plastorribosomas 70S",
    essentialConcept: "Plastidios fotosintéticos con doble membrana y discos tilacoidales donde se transforma la energía de la luz en energía química.",
    x: 480,
    y: 530,
    connections: ["tema-19"],
  },

  // ==========================================
  // CITOLOGÍA II - MÓDULO IV: ARQUITECTURA NUCLEAR & CARIOTECA (22 - 25)
  // ==========================================
  {
    id: "tema-22",
    number: 22,
    title: "El Núcleo Interfásico: Arquitectura General",
    module: "IV",
    moduleName: "Arquitectura Nuclear & Carioteca",
    category: "Arquitectura Nuclear",
    keywords: "Célula interfásica, carioteca, nucleoplasma, cromatina, nucleolo, compartimentación del genoma",
    essentialConcept: "Centro de control de la célula eucariota donde se custodia, replica y transcribe la información genética.",
    x: 660,
    y: 250,
    connections: ["tema-23", "tema-25", "tema-26"],
  },
  {
    id: "tema-23",
    number: 23,
    title: "Carioteca y Complejo del Poro Nuclear (NPC)",
    module: "IV",
    moduleName: "Arquitectura Nuclear & Carioteca",
    category: "Envoltura Nuclear",
    keywords: "Membrana nuclear interna y externa, espacio perinuclear, nucleoporinas, simetría octogonal, lámina nuclear",
    essentialConcept: "Doble membrana continua con el RER que aísla el genoma y cuenta con poros de nucleoporinas para el intercambio selectivo.",
    x: 620,
    y: 350,
    connections: ["tema-14", "tema-22", "tema-24"],
  },
  {
    id: "tema-24",
    number: 24,
    title: "Transporte Nuclear: Importinas y Señal NLS",
    module: "IV",
    moduleName: "Arquitectura Nuclear & Carioteca",
    category: "Transporte Nuclear",
    keywords: "Señal de localización nuclear NLS, señal NES, importinas alfa/beta, exportinas, proteína G Ran-GTP/Ran-GDP",
    essentialConcept: "Mecanismo molecular activo mediado por importinas/exportinas y la GTPasa Ran que dirige macromoléculas a través del poro.",
    x: 760,
    y: 340,
    connections: ["tema-23", "tema-25"],
  },
  {
    id: "tema-25",
    number: 25,
    title: "Cariolinfa y Lámina Nuclear",
    module: "IV",
    moduleName: "Arquitectura Nuclear & Carioteca",
    category: "Matriz Nuclear",
    keywords: "Nucleoplasma, cariolinfa, jugo nuclear, lámina nuclear filamentos intermedios laminas A, B, C, anclaje de cromatina",
    essentialConcept: "Medio coloidal nuclear y malla de filamentos intermedios subyacente a la carioteca que da forma y estabilidad estructural al núcleo.",
    x: 880,
    y: 290,
    connections: ["tema-22", "tema-23", "tema-26"],
  },

  // ==========================================
  // CITOLOGÍA II - MÓDULO V: CROMATINA, NUCLEOLO & GENOMA (26 - 30)
  // ==========================================
  {
    id: "tema-26",
    number: 26,
    title: "Cromatina y Niveles de Compactación",
    module: "V",
    moduleName: "Cromatina, Nucleolo & Genoma",
    category: "Genoma & Empaquetamiento",
    keywords: "ADN bicatenario, octámero de histonas H2A, H2B, H3, H4, nucleosoma cuentas de collar, histona H1, fibra de 30 nm solenoide",
    essentialConcept: "Complejo de ADN y proteínas histónicas que condensa los 2 metros de genoma lineal para que quepan ordenadamente en el núcleo.",
    x: 740,
    y: 440,
    connections: ["tema-22", "tema-27", "tema-28", "tema-29"],
  },
  {
    id: "tema-27",
    number: 27,
    title: "Eucromatina vs. Heterocromatina",
    module: "V",
    moduleName: "Cromatina, Nucleolo & Genoma",
    category: "Regulación Epigenética",
    keywords: "Eucromatina transcripcionalmente activa descondensada, heterocromatina constitutiva y facultativa, corpúsculo de Barr inactivación X",
    essentialConcept: "Diferenciación funcional de la cromatina: la eucromatina está abierta para ser leída y la heterocromatina compactada y silenciada.",
    x: 880,
    y: 420,
    connections: ["tema-26", "tema-30"],
  },
  {
    id: "tema-28",
    number: 28,
    title: "El Nucleolo y Biogénesis Ribosomal",
    module: "V",
    moduleName: "Cromatina, Nucleolo & Genoma",
    category: "Fábrica Ribosomal",
    keywords: "Organizador nucleolar NOR, cromosomas acrocéntricos 13, 14, 15, 21, 22, ARNr precursor 45S, ensamblado subunidades 40S y 60S",
    essentialConcept: "Zona densa del núcleo sin membrana dedicada a transcribir ARN ribosomal y ensamblar las subunidades que viajarán al citosol.",
    x: 640,
    y: 480,
    connections: ["tema-12", "tema-26"],
  },
  {
    id: "tema-29",
    number: 29,
    title: "Morfología del Cromosoma",
    module: "V",
    moduleName: "Cromatina, Nucleolo & Genoma",
    category: "Cromosomas Celulares",
    keywords: "Centrómero constricción primaria, cinetocoro huso mitótico, telómeros repetitivos, brazos p y q, metacéntrico, acrocéntrico, telocéntrico",
    essentialConcept: "Máximo grado de empaquetamiento de la cromatina para su transporte exacto; posee centrómero, telómeros y cinetocoros.",
    x: 790,
    y: 530,
    connections: ["tema-26", "tema-30"],
  },
  {
    id: "tema-30",
    number: 30,
    title: "Cariotipo y Organización del Genoma",
    module: "V",
    moduleName: "Cromatina, Nucleolo & Genoma",
    category: "Genética Citológica",
    keywords: "Cariotipo humano 46 cromosomas, autosomas 44, cromosomas sexuales XX/XY, células somáticas diploides 2n y gametos haploides n",
    essentialConcept: "Representación ordenada del número, tamaño y forma de los cromosomas de una especie que define la ploidía celular.",
    x: 930,
    y: 520,
    connections: ["tema-27", "tema-29"],
  },
];

export const INITIAL_TOPICS: TopicNode[] = INITIAL_TOPICS_RAW.map((t) => ({
  ...t,
  subtopics: TOPIC_SUBTOPICS[t.id] || [
    `Conceptos esenciales de ${t.title}`,
    `Piezas moleculares y mecanismo de ${t.title}`,
    `Puntos clave y distinciones de ${t.title}`,
  ],
}));
